# Generated by Django 5.2.11 on 2026-02-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotationModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("document_id", models.CharField(db_index=True, max_length=64)),
                ("label_id", models.CharField(db_index=True, max_length=64)),
                ("annotation_type", models.TextField()),
                ("start_offset", models.IntegerField(blank=True, null=True)),
                ("end_offset", models.IntegerField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("page", models.IntegerField(blank=True, null=True)),
                ("x", models.FloatField(blank=True, null=True)),
                ("y", models.FloatField(blank=True, null=True)),
                ("width", models.FloatField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                ("key_text", models.TextField(blank=True, null=True)),
                ("key_start", models.IntegerField(blank=True, null=True)),
                ("key_end", models.IntegerField(blank=True, null=True)),
                ("value_text", models.TextField(blank=True, null=True)),
                ("value_start", models.IntegerField(blank=True, null=True)),
                ("value_end", models.IntegerField(blank=True, null=True)),
                ("entity_type", models.TextField(blank=True, null=True)),
                ("normalized_value", models.TextField(blank=True, null=True)),
                ("created_by", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("row_index", models.IntegerField(blank=True, null=True)),
                ("group_id", models.TextField(blank=True, db_index=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "annotations",
            },
        ),
        migrations.CreateModel(
            name="BenchmarkDatasetModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.TextField()),
                ("document_type_id", models.CharField(db_index=True, max_length=64)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_by", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "benchmark_datasets",
            },
        ),
        migrations.CreateModel(
            name="BenchmarkRunModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("dataset_id", models.CharField(db_index=True, max_length=64)),
                ("document_type_id", models.CharField(max_length=64)),
                (
                    "prompt_version_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "baseline_run_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("total_documents", models.IntegerField()),
                ("successful_documents", models.IntegerField()),
                ("failed_documents", models.IntegerField()),
                ("overall_metrics", models.JSONField(default=dict)),
                ("split_metrics", models.JSONField(default=dict)),
                ("subtype_scorecards", models.JSONField(default=dict)),
                ("confidence_intervals", models.JSONField(default=dict)),
                ("drift_delta", models.JSONField(blank=True, default=dict, null=True)),
                ("gate_results", models.JSONField(blank=True, default=list, null=True)),
                ("passed_gates", models.BooleanField(default=True)),
                ("errors", models.JSONField(blank=True, default=list, null=True)),
                ("use_llm_refinement", models.BooleanField(default=True)),
                ("use_structured_output", models.BooleanField(default=False)),
                ("evaluated_by", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "db_table": "benchmark_runs",
            },
        ),
        migrations.CreateModel(
            name="ClassificationModel",
            fields=[
                (
                    "document_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("document_type_id", models.CharField(db_index=True, max_length=64)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("labeled_by", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "classifications",
            },
        ),
        migrations.CreateModel(
            name="EvaluationModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("document_id", models.CharField(db_index=True, max_length=64)),
                ("document_type_id", models.CharField(db_index=True, max_length=64)),
                (
                    "prompt_version_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "schema_version_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("comparator_mode", models.TextField(default="normalized")),
                ("metrics", models.JSONField(default=dict)),
                ("extraction_time_ms", models.IntegerField(blank=True, null=True)),
                ("evaluated_by", models.TextField(blank=True, null=True)),
                ("evaluated_at", models.DateTimeField(db_index=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("field_prompt_versions", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "evaluations",
            },
        ),
        migrations.CreateModel(
            name="ExtractionModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "document_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("document_type_id", models.CharField(max_length=64)),
                (
                    "schema_version_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "prompt_version_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("extracted_data", models.JSONField(default=dict)),
                ("extracted_at", models.DateTimeField()),
            ],
            options={
                "db_table": "extractions",
            },
        ),
        migrations.CreateModel(
            name="FeedbackModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("document_id", models.CharField(max_length=64)),
                ("label_id", models.CharField(db_index=True, max_length=64)),
                ("label_name", models.TextField(blank=True, null=True)),
                ("text", models.TextField()),
                ("start_offset", models.IntegerField()),
                ("end_offset", models.IntegerField()),
                ("feedback_type", models.TextField(db_index=True)),
                ("source", models.TextField()),
                ("embedding", models.JSONField(blank=True, default=list, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "feedback",
            },
        ),
        migrations.CreateModel(
            name="FieldPromptVersionModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.TextField()),
                ("document_type_id", models.CharField(db_index=True, max_length=64)),
                ("field_name", models.TextField(db_index=True)),
                ("extraction_prompt", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("created_by", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "field_prompt_versions",
            },
        ),
        migrations.CreateModel(
            name="GlobalFieldModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.TextField(db_index=True, unique=True)),
                ("type", models.TextField()),
                ("prompt", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("extraction_model", models.TextField(blank=True, null=True)),
                ("ocr_engine", models.TextField(blank=True, null=True)),
                ("created_by", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "global_fields",
            },
        ),
        migrations.CreateModel(
            name="LLMProviderSettingsModel",
            fields=[
                ("provider", models.TextField(primary_key=True, serialize=False)),
                ("api_key_override", models.TextField(blank=True, null=True)),
                ("last_test_status", models.TextField(default="unknown")),
                ("last_tested_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "llm_provider_settings",
            },
        ),
        migrations.CreateModel(
            name="ModelStatusModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("trained_at", models.DateTimeField()),
                ("sample_count", models.IntegerField()),
                ("positive_samples", models.IntegerField(default=0)),
                ("negative_samples", models.IntegerField(default=0)),
                ("labels_count", models.IntegerField(default=0)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("model_path", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "model_status",
            },
        ),
        migrations.CreateModel(
            name="PromptVersionModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.TextField()),
                (
                    "document_type_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("system_prompt", models.TextField()),
                ("user_prompt_template", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("created_by", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "prompt_versions",
            },
        ),
        migrations.CreateModel(
            name="SchemaVersionModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("document_type_id", models.CharField(db_index=True, max_length=64)),
                ("schema_fields", models.JSONField(default=list)),
                ("system_prompt", models.TextField(blank=True, null=True)),
                ("post_processing", models.TextField(blank=True, null=True)),
                ("extraction_model", models.TextField(blank=True, null=True)),
                ("ocr_engine", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("created_by", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "schema_versions",
            },
        ),
        migrations.CreateModel(
            name="BenchmarkDatasetDocumentModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("dataset_id", models.CharField(db_index=True, max_length=64)),
                ("document_id", models.CharField(max_length=64)),
                ("split", models.TextField(db_index=True, default="test")),
                ("tags", models.JSONField(default=list)),
                ("doc_subtype", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "benchmark_dataset_documents",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataset_id", "document_id"),
                        name="unique_dataset_document",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeploymentVersionModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("project_id", models.TextField()),
                ("version", models.TextField()),
                ("document_type_id", models.CharField(max_length=64)),
                ("document_type_name", models.TextField()),
                (
                    "schema_version_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "prompt_version_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("system_prompt", models.TextField(blank=True, null=True)),
                ("user_prompt_template", models.TextField(blank=True, null=True)),
                ("schema_fields", models.JSONField(default=list)),
                ("field_prompt_versions", models.JSONField(default=dict)),
                ("model", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_by", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "deployment_versions",
                "indexes": [
                    models.Index(
                        fields=["project_id", "is_active"],
                        name="idx_deploy_project_active",
                    ),
                    models.Index(
                        fields=["project_id", "created_at"],
                        name="idx_deploy_project_created",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project_id", "version"),
                        name="idx_deployment_versions_project_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LabelModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.TextField()),
                ("color", models.TextField(default="#3b82f6")),
                ("description", models.TextField(blank=True, null=True)),
                ("shortcut", models.TextField(blank=True, null=True)),
                ("entity_type", models.TextField(blank=True, null=True)),
                (
                    "document_type_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "labels",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "document_type_id"),
                        name="idx_labels_name_scope_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LLMProviderModelModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("provider", models.TextField()),
                ("model_id", models.TextField()),
                ("display_name", models.TextField(blank=True, null=True)),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "llm_provider_models",
                "indexes": [
                    models.Index(
                        fields=["provider", "is_enabled"],
                        name="idx_llm_provider_enabled",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "model_id"), name="llm_provider_model_pk"
                    )
                ],
            },
        ),
    ]
