# Generated by Django 5.2.11 on 2026-02-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_data", "0002_annotationmodel_benchmarkdatasetmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentModel",
            fields=[
                ("id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("filename", models.CharField(db_index=True, max_length=255)),
                ("file_type", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("date_extracted", models.DateField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("page_count", models.IntegerField(blank=True, null=True)),
                ("word_count", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="documents_created_291bb4_idx"),
                    models.Index(fields=["filename"], name="documents_filenam_64880e_idx"),
                    models.Index(fields=["file_type"], name="documents_file_ty_4b3ae1_idx"),
                    models.Index(fields=["date_extracted"], name="documents_date_ex_4789ff_idx"),
                ],
            },
        ),
    ]
