# Generated by Django 5.2.11 on 2026-02-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_data', '0004_remove_labelling_tables'),
    ]

    operations = [
        # No operations needed - models were already removed in 0004_remove_labelling_tables
        # This migration just updates Django's migration state to reflect code changes
    ]
