# Generated by Django 5.2.11 on 2026-02-17 20:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_data", "0005_remove_chunks_timeline_entities"),
    ]

    operations = [
        # No-op migration - these models were already removed in previous migrations
        # This migration exists only to update Django's migration state
    ]
