# Generated by Django 5.2.11 on 2026-02-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_data", "0008_add_evaluation_run_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroundTruthAnnotationModel",
            fields=[
                ("id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("document_id", models.CharField(db_index=True, max_length=64)),
                ("field_name", models.CharField(db_index=True, max_length=255)),
                ("value", models.JSONField()),
                ("annotation_type", models.CharField(max_length=20)),
                ("annotation_data", models.JSONField()),
                ("confidence", models.FloatField(default=1.0)),
                ("labeled_by", models.CharField(max_length=50)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ground_truth_annotations",
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name="AnnotationModel"),
                migrations.DeleteModel(name="BenchmarkDatasetDocumentModel"),
                migrations.DeleteModel(name="BenchmarkDatasetModel"),
                migrations.DeleteModel(name="BenchmarkRunModel"),
                migrations.DeleteModel(name="EvaluationModel"),
                migrations.DeleteModel(name="FeedbackModel"),
                migrations.DeleteModel(name="LabelModel"),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="azure_di_analysis",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentmodel",
            name="azure_di_status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AddIndex(
            model_name="groundtruthannotationmodel",
            index=models.Index(
                fields=["document_id", "field_name"], name="ground_trut_documen_5a06b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groundtruthannotationmodel",
            index=models.Index(
                fields=["document_id", "created_at"], name="ground_trut_documen_bcfe0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groundtruthannotationmodel",
            index=models.Index(fields=["labeled_by"], name="ground_trut_labeled_b566c6_idx"),
        ),
    ]
