# Generated by Django 5.2.11 on 2026-02-18 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_data', '0008_add_ground_truth_and_ocr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnotationModel',
        ),
        migrations.DeleteModel(
            name='BenchmarkDatasetDocumentModel',
        ),
        migrations.DeleteModel(
            name='BenchmarkDatasetModel',
        ),
        migrations.DeleteModel(
            name='BenchmarkRunModel',
        ),
        migrations.DeleteModel(
            name='EvaluationModel',
        ),
        migrations.DeleteModel(
            name='FeedbackModel',
        ),
        migrations.DeleteModel(
            name='LabelModel',
        ),
        migrations.RenameIndex(
            model_name='groundtruthannotationmodel',
            new_name='ground_trut_documen_5a06b7_idx',
            old_name='ground_truth_doc_field_idx',
        ),
        migrations.RenameIndex(
            model_name='groundtruthannotationmodel',
            new_name='ground_trut_documen_bcfe0e_idx',
            old_name='ground_truth_doc_created_idx',
        ),
        migrations.RenameIndex(
            model_name='groundtruthannotationmodel',
            new_name='ground_trut_labeled_b566c6_idx',
            old_name='ground_truth_labeled_by_idx',
        ),
    ]
