# Generated by Django 5.2.9 on 2025-12-18 08:33

import backend.users.managers
import backend.users.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, help_text='Your first name.', max_length=250, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, help_text='Your last name.', max_length=250, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(blank=True, help_text='Your date of birth for age verification and personalization.', null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Your gender identity.', max_length=10, verbose_name='Gender')),
                ('email', models.EmailField(help_text='Your email address, used for login.', max_length=254, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(blank=True, help_text='Your contact phone number.', max_length=20, verbose_name='Phone Number')),
                ('profile_image', models.ImageField(blank=True, help_text='Upload a profile image.', null=True, upload_to=backend.users.models.upload_user_profile_image, verbose_name='Profile Image')),
                ('bio', models.TextField(blank=True, help_text='A short description about yourself.', verbose_name='Bio')),
                ('website', models.URLField(blank=True, help_text='Your personal or professional website URL.', verbose_name='Website')),
                ('platform_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('de', 'German'), ('it', 'Italian'), ('fr', 'French'), ('ro', 'Romanian')], default='en', help_text='The language you prefer for the platform interface.', max_length=5, verbose_name='Platform Language')),
                ('timezone', models.CharField(default='UTC', help_text='Your preferred timezone for displaying dates and times.', max_length=50, verbose_name='Timezone')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', backend.users.managers.UserManager()),
            ],
        ),
    ]
