# Generated by Django 5.2.9 on 2025-12-18 09:58

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the API key.', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the API key is active.', verbose_name='Is Active')),
                ('key', models.CharField(help_text='The API key string used for authentication.', max_length=250, unique=True, verbose_name='API Key')),
                ('name', models.CharField(help_text='A name to identify the API key.', max_length=250, verbose_name='Name')),
                ('valid_until', models.DateTimeField(blank=True, help_text='The date and time until which the API key is valid. Leave blank for no expiration.', null=True, verbose_name='Valid Until')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the API key was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the API key was last updated.', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAPIKey',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for the API key.', verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the API key is active.', verbose_name='Is Active')),
                ('key', models.CharField(db_index=True, help_text='The API key string used for authentication.', max_length=250, verbose_name='API Key')),
                ('name', models.CharField(help_text='A name to identify the API key.', max_length=250, verbose_name='Name')),
                ('valid_until', models.DateTimeField(blank=True, help_text='The date and time until which the API key is valid. Leave blank for no expiration.', null=True, verbose_name='Valid Until')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='The date and time when the API key was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='The date and time when the API key was last updated.', verbose_name='Updated At')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical API Key',
                'verbose_name_plural': 'historical API Keys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the notification.', primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The content of the notification.', verbose_name='Message')),
                ('importance', models.CharField(choices=[('standard', 'Standard'), ('important', 'Important'), ('critical', 'Critical')], default='standard', help_text='The importance level of the notification.', max_length=10, verbose_name='Importance')),
                ('action_link', models.URLField(blank=True, help_text='A URL that the user can follow for more information or to take action.', null=True, verbose_name='Action Link')),
                ('is_read', models.BooleanField(default=False, help_text='Indicates whether the notification has been read.', verbose_name='Is Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the notification was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the notification was last updated.', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_idx'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(help_text='The user who owns this API key.', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalapikey',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalapikey',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user who owns this API key.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(help_text='The user to whom this notification belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['user'], name='apikey_user_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notif_user_isread_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='notif_user_createdat_idx'),
        ),
    ]
