# Generated by Django 5.2.9 on 2025-12-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_apikey_historicalapikey_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive notifications via email.', verbose_name='Email Notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_emails',
            field=models.BooleanField(default=False, help_text='Receive promotional and marketing emails.', verbose_name='Marketing Emails'),
        ),
        migrations.AddField(
            model_name='user',
            name='push_notifications',
            field=models.BooleanField(default=True, help_text='Receive push notifications in your browser.', verbose_name='Push Notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='security_alerts',
            field=models.BooleanField(default=True, help_text='Important security and account alerts.', verbose_name='Security Alerts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Europe/London', help_text='Your preferred timezone for displaying dates and times.', max_length=200, verbose_name='Timezone'),
        ),
    ]
