"""Pydantic models for Unstructured Unlocked."""

from uu_backend.models.annotation import (
    AnnotationSuggestion,
    AnnotationSuggestionResponse,
    AnnotationType,
    ApproveAnnotationRequest,
    BoundingBoxData,
    GroundTruthAnnotation,
    GroundTruthAnnotationCreate,
    GroundTruthAnnotationListResponse,
    GroundTruthAnnotationResponse,
    GroundTruthAnnotationUpdate,
    TableRowData,
    TableRowFieldData,
    TextSpanData,
)
from uu_backend.models.document import (
    Document,
    DocumentMetadata,
    IngestResponse,
)
from uu_backend.models.evaluation import (
    EvaluationMetrics,
    EvaluationResult,
    EvaluationRun,
    EvaluationRunCreate,
    EvaluationRunListResponse,
    EvaluationRunResponse,
    EvaluationSummary,
    FieldComparison,
    FieldMetrics,
    FlattenedMetrics,
    InstanceComparison,
    InstanceMetrics,
    MatchResult,
    MatchType,
)
from uu_backend.models.prompt import (
    FieldPromptVersion,
    PromptVersion,
)
from uu_backend.models.taxonomy import (
    Classification,
    ClassificationCreate,
    ClassificationResponse,
    DocumentType,
    DocumentTypeCreate,
    DocumentTypeListResponse,
    DocumentTypeResponse,
    DocumentTypeUpdate,
    ExtractedField,
    ExtractionResult,
    FieldType,
    SchemaField,
)

__all__ = [
    "Document",
    "DocumentMetadata",
    "IngestResponse",
    # Taxonomy models
    "Classification",
    "ClassificationCreate",
    "ClassificationResponse",
    "DocumentType",
    "DocumentTypeCreate",
    "DocumentTypeListResponse",
    "DocumentTypeResponse",
    "DocumentTypeUpdate",
    "ExtractedField",
    "ExtractionResult",
    "FieldType",
    "SchemaField",
    # Prompt models
    "PromptVersion",
    "FieldPromptVersion",
    # Annotation models
    "AnnotationType",
    "AnnotationSuggestion",
    "AnnotationSuggestionResponse",
    "ApproveAnnotationRequest",
    "BoundingBoxData",
    "GroundTruthAnnotation",
    "GroundTruthAnnotationCreate",
    "GroundTruthAnnotationListResponse",
    "GroundTruthAnnotationResponse",
    "GroundTruthAnnotationUpdate",
    "TableRowData",
    "TableRowFieldData",
    "TextSpanData",
    # Evaluation models
    "EvaluationMetrics",
    "EvaluationResult",
    "EvaluationRun",
    "EvaluationRunCreate",
    "EvaluationRunListResponse",
    "EvaluationRunResponse",
    "EvaluationSummary",
    "FieldComparison",
    "FieldMetrics",
    "FlattenedMetrics",
    "InstanceComparison",
    "InstanceMetrics",
    "MatchResult",
    "MatchType",
]
